export default {
  login: "Samson-Ludo",
  id: 43629180,
  node_id: "MDQ6VXNlcjQzNjI5MTgw",
  avatar_url: "https://avatars1.githubusercontent.com/u/43629180?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/Samson-Ludo",
  html_url: "https://github.com/Samson-Ludo",
  followers_url: "https://api.github.com/users/Samson-Ludo/followers",
  following_url:
    "https://api.github.com/users/Samson-Ludo/following{/other_user}",
  gists_url: "https://api.github.com/users/Samson-Ludo/gists{/gist_id}",
  starred_url:
    "https://api.github.com/users/Samson-Ludo/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/Samson-Ludo/subscriptions",
  organizations_url: "https://api.github.com/users/Samson-Ludo/orgs",
  repos_url: "https://api.github.com/users/Samson-Ludo/repos",
  events_url: "https://api.github.com/users/Samson-Ludo/events{/privacy}",
  received_events_url:
    "https://api.github.com/users/Samson-Ludo/received_events",
  type: "User",
  site_admin: false,
  name: "Samson Okaludo",
  company: null,
  blog: "http://samsonludo.netlify.com/",
  location: null,
  email: null,
  hireable: true,
  bio: "Software Developer",
  twitter_username: null,
  public_repos: 34,
  public_gists: 0,
  followers: 4,
  following: 19,
  created_at: "2018-09-27T03:18:37Z",
  updated_at: "2021-01-01T09:25:29Z",
};
